version: '3.9'

services:
  flink-jm:
    hostname: flink-jm
    container_name: flink-jm
    build:
      context: ./flink-jm
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.memory.process.size: 1024mb
        jobmanager.memory.heap.size: 128mb
        jobmanager.memory.off-heap.size: 128mb
        jobmanager.memory.jvm-metaspace.size: 256mb
        jobmanager.memory.jvm-overhead.min: 192mb
        jobmanager.memory.jvm-overhead.max: 1024mb
        metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
        metrics.reporter.prom.port: 9260
  flink-tm:
    hostname: "flink-tm"
    build:
      context: flink-tm
    deploy:
      replicas: 10
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jm
        taskmanager.numberOfTaskSlots: 3
        taskmanager.memory.process.size: 1024mb
        taskmanager.memory.task.heap.size: 105mb
        taskmanager.memory.managed.size: 417mb
        taskmanager.memory.framework.heap.size: 64mb
        taskmanager.memory.framework.off-heap.size: 64mb
        taskmanager.memory.task.off-heap.size: 64mb
        taskmanager.memory.network.min: 32mb
        taskmanager.memory.network.max: 512mb
        taskmanager.memory.jvm-metaspace.size: 128mb
        taskmanager.memory.jvm-overhead.min: 96mb
        taskmanager.memory.jvm-overhead.max: 512mb
        metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
        metrics.reporter.prom.port: 9260
    depends_on:
      - flink-jm
  flink-injector:
    build:
      context: flink-injector
    deploy:
      replicas: 5
    environment:
      FLINK_JM_ADDRESS: "flink-jm"
      FAKE_JOB_PACK_COUNT: 2
    depends_on:
      - flink-jm
  prometheus:
    hostname: prometheus
    container_name: prometheus
    build:
      context: prometheus
    volumes:
      - ${PWD}/prometheus/files/prometheus.yml:/app/prometheus/prometheus.yml
    depends_on:
      - flink-jm
      - flink-tm
  grafana:
    container_name: grafana
    hostname: grafana
    build:
      context: grafana
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/grafana/files/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
      - ${PWD}/grafana/files/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:ro
      - ${PWD}/grafana/files/flink.json:/var/lib/grafana/dashboards/flink.json:ro
    depends_on:
      - prometheus
