global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "flink-task-manager"
    dns_sd_configs:
      - names:
          - 'flink-tm'
        refresh_interval: 10s
        type: 'A'
        port: 9260
    metrics_path: /
  - job_name: "flink-job-manger"
    static_configs:
      - targets: [ "flink-jm:9260" ]
    metrics_path: /